#!/bin/sh
#
#    99-footer - write the admin's footer to the MOTD
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
 
[ -f /etc/motd.tail ] && cat /etc/motd.tail || true
